name: Package Wordpress Plugin

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    package:
        name: Package Plugin Zip
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Package Filename
              id: package-id
              run: |
                    echo "zipFilename=wp-password-redirect.zip" 
                    echo "artifactFilename=${{ github.workspace }}/$filename"
                    echo "releaseFilename=wp-password-redirect-${{ github.ref }}.zip"
            - uses: vimtor/action-zip@v1.2
              name: zip
              with:
                files: src/wp-password-redirect/ 
                dest: ${{ steps.package-id.outputs.zipFilename}}

            - uses: actions/upload-artifact@v4
              with:
                name: plugin-package
                path: ${{ steps.package-id.outputs.artifactFilename}}

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                generate_release_notes: true
                files: ${{ steps.package-id.outputs.releaseFilename }}

