name: Package Wordpress Plugin

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    package:
        name: Package Plugin Zip
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Package Filename
              id: packageId
              run: | 
                    if [[ ${{ github.ref }} == refs/tags/* ]] 
                    then
                        zipFilename="wp-password-redirect-${{ github.ref }}.zip"
                    else
                        zipFilename="wp-password-redirect.zip"
                    fi
                    echo "zipFilename=${zipFilename}"
                    echo "artifactFilename=${{ github.workspace }}/${zipFilename}"
                    
            - uses: vimtor/action-zip@v1.2
              name: zip
              with:
                files: ${{ github.workspace }}/src/ 
                dest: ${{ steps.packageId.outputs.zipFilename }}

            - name: debug
              run: |
                    tree ${{ github.workspace }}

            - uses: actions/upload-artifact@v4
              with:
                name: plugin-package
                path: ${{ steps.packageId.outputs.artifactFilename }}

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                generate_release_notes: true
                files: ${{ steps.packageId.outputs.artifactFilename }}

